name: send-audit

on:
  workflow_dispatch: 
  push:
    branches: [ main ]

jobs:
  send-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare payload
        run: |
          cat > payload.json <<EOF
          {
            "repo": "${{ github.repository }}",
            "actor": "${{ github.actor }}",
            "event": "${{ github.event_name }}",
            "sha": "${{ github.sha }}",
            "ref": "${{ github.ref }}",
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "custom_message": "This is a real test event"
          }
          EOF

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send to SQS
        run: |
          aws sqs send-message \
            --queue-url "${{ secrets.SQS_QUEUE_URL }}" \
            --message-body file://payload.json
